project_id = "pahsxfzernyylrgfxcmp"

[functions.chat]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.admin-data]
verify_jwt = false

[functions.get-messages]
verify_jwt = false

[functions.get-conversations]
verify_jwt = false

[functions.get-user-by-email]
verify_jwt = false
